#!/usr/bin/env python3
"""Rewrite src/ui/test_ui_case_times.h from a full test run.

    python scripts/ui-case-times.py <build>/Testing/Temporary/LastTest.log [more logs]

The screen suite packs its cases into ctest shards by these times, so
regenerate after a run when the shards stop finishing together. With
several logs a case takes the longest time any of them measured.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "ui", "test_ui_screens.c")
OUT = os.path.join(ROOT, "src", "ui", "test_ui_case_times.h")

CASE_RE = re.compile(r"RUN_UI_TEST\(\s*(\w+)\s*\)")
RESULT_RE = re.compile(r"(?:PASS|SKIP|took)\s+([0-9.]+) ms")


def case_names():
    with open(SRC, encoding="utf-8") as f:
        return set(CASE_RE.findall(f.read()))


def measure(log_path, names, times):
    current = None
    with open(log_path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if line.startswith("  "):
                word = line[2:].split(" ", 1)[0].strip()
                if word in names:
                    current = word
            if current:
                m = RESULT_RE.search(line)
                if m:
                    ms = int(round(float(m.group(1))))
                    times[current] = max(ms, times.get(current, 0))
                    current = None


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    names = case_names()
    times = {}
    for log in argv[1:]:
        measure(log, names, times)
    if not times:
        print("no screen suite case times found in", ", ".join(argv[1:]))
        return 1
    rows = sorted(times.items(), key=lambda kv: (-kv[1], kv[0]))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by scripts/ui-case-times.py from a full run. Measured\n"
                " * milliseconds per screen suite case, which the suite packs into\n"
                " * ctest shards by. Regenerate, do not edit. */\n")
        f.write("#ifndef TEST_UI_CASE_TIMES_H\n#define TEST_UI_CASE_TIMES_H\n\n")
        f.write("typedef struct { const char *name; int ms; } UiCaseTime;\n\n")
        f.write("static const UiCaseTime g_ui_case_times[] = {\n")
        for name, ms in rows:
            f.write('    { "%s", %d },\n' % (name, ms))
        f.write("};\n\n#endif\n")
    total = sum(times.values())
    missing = len(names - set(times))
    print("%d cases, %.1f s in all, %d with no time, longest %s at %.1f s"
          % (len(times), total / 1000.0, missing, rows[0][0], rows[0][1] / 1000.0))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
